metadata.format.version = "1.1"

[versions]

# CompileOnly dependencies
velocity = "3.2.0-SNAPSHOT"

# Gradle Plugins
blossom = "1.3.1"
shadow = "7.1.2"
runvelocity = "2.0.1"

# Utility Libraries
configurate = "4.1.2"
libby = "43d25ade72"
bstats = "3.0.0"

# Required by Configurate 4
geantyref = "1.3.13"

miniplaceholders = "2.0.0"

[libraries]

# Compile Only Dependencies
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }

configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
configurate-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }

libby = { group = "com.github.AlessioDP.libby", name = "libby-velocity", version.ref = "libby" }

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }